name: regalTown

on:
  workflow_dispatch:
  schedule:
     - cron: '1,30 1-23 * * *'
  watch:
    types: book

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          npm install got #tough-cookie
      - name: '运行 【regalTown】'
        run: |
          node task/regalTown.js
        env:
          fhxzurl: ${{ secrets.fhxzurl }}
          fhxzhd: ${{ secrets.fhxzhd }}
